//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ERP.Api.Migrations.Application;

/// <inheritdoc />
public partial class Add_UserId_Reference : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DELETE FROM erp_system.products;
            DELETE FROM erp_system.categories;
            """
            );

        migrationBuilder.DropIndex(
            name: "ix_categories_slug",
            schema: "erp_system",
            table: "categories");

        migrationBuilder.AddColumn<string>(
            name: "user_id",
            schema: "erp_system",
            table: "products",
            type: "character varying(500)",
            maxLength: 500,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "user_id",
            schema: "erp_system",
            table: "categories",
            type: "character varying(500)",
            maxLength: 500,
            nullable: false,
            defaultValue: "");

        migrationBuilder.CreateIndex(
            name: "ix_products_user_id",
            schema: "erp_system",
            table: "products",
            column: "user_id");

        migrationBuilder.CreateIndex(
            name: "ix_categories_user_id_name",
            schema: "erp_system",
            table: "categories",
            columns: new[] { "user_id", "name" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_categories_user_id_slug",
            schema: "erp_system",
            table: "categories",
            columns: new[] { "user_id", "slug" },
            unique: true);

        migrationBuilder.AddForeignKey(
            name: "fk_categories_users_user_id",
            schema: "erp_system",
            table: "categories",
            column: "user_id",
            principalSchema: "erp_system",
            principalTable: "users",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade);

        migrationBuilder.AddForeignKey(
            name: "fk_products_users_user_id",
            schema: "erp_system",
            table: "products",
            column: "user_id",
            principalSchema: "erp_system",
            principalTable: "users",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_categories_users_user_id",
            schema: "erp_system",
            table: "categories");

        migrationBuilder.DropForeignKey(
            name: "fk_products_users_user_id",
            schema: "erp_system",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_user_id",
            schema: "erp_system",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_categories_user_id_name",
            schema: "erp_system",
            table: "categories");

        migrationBuilder.DropIndex(
            name: "ix_categories_user_id_slug",
            schema: "erp_system",
            table: "categories");

        migrationBuilder.DropColumn(
            name: "user_id",
            schema: "erp_system",
            table: "products");

        migrationBuilder.DropColumn(
            name: "user_id",
            schema: "erp_system",
            table: "categories");

        migrationBuilder.CreateIndex(
            name: "ix_categories_slug",
            schema: "erp_system",
            table: "categories",
            column: "slug",
            unique: true);
    }
}
