name: erp-system
services:
  erp.api:
    image: ${DOCKER_REGISTRY-}erpapi
    build:
      context: .
      dockerfile: ERP.Api/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081
    depends_on:
      - erp.postgres

  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - erp.api
    environment:
      - API_URL=http://erp.api:8080/api


  erp.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: erpsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - ./.containers/postgres_data:/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 15432:5432
volumes:
  postgres_data:
    external: true
